In [1]:
import numpy as np
import pandas as pd

# **1. Creating a DataFrame**

**From Dictionary**

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**From List of Lists**

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [5]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [6]:
col = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns =col)

In [7]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# **2. Selection and Indexing of Columns**

**Single Column**

In [8]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

**Multiple Columns**

In [9]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

# **3. Creating a new Column**

In [10]:
df2["Designation"] = ["Doctor", "Eng.", "Doctor", "Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

# **4. Removing Columns**

**Drop Row**

In [11]:
df2.drop(0, axis=0)   # removes row index 0

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

**Drop Column**

In [12]:
df2.drop("Salary", axis=1)

    Name  Age      City Designation
0   John   28  New York      Doctor
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin      Doctor
3  Linda   42    London        Eng.

In [13]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [14]:
df2.drop("Salary", axis=1, inplace=True)  #use inplace=True, to modify original DataFrame

In [15]:
df2

    Name  Age      City Designation
0   John   28  New York      Doctor
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin      Doctor
3  Linda   42    London        Eng.

# **5. Selecting Rows**

**Using loc (label-based)**

In [16]:
df2.loc[[0, 1]]

   Name  Age      City Designation
0  John   28  New York      Doctor
1  Anna   34     Paris        Eng.

**Using iloc (index-based)**

In [17]:
df2.iloc[3]

Name            Linda
Age                42
City           London
Designation      Eng.
Name: 3, dtype: object

# **6. Selecting Rows + Columns Together**

In [18]:
df2.loc[[0, 1], ["City", "Designation"]]  #Single-step selection (rows + columns together) / Faster + safer (direct access, no intermediate copy)

       City Designation
0  New York      Doctor
1     Paris        Eng.

In [19]:
df.loc[[0,1]][["City","Salary"]]   #Two-step selection (first rows, then columns) / Slightly slower + risky (creates temporary DataFrame, can cause issues in some cases)

       City  Salary
0  New York   65000
1     Paris   70000

# **7. Conditional Selection (Filtering)**

In [20]:
df2

    Name  Age      City Designation
0   John   28  New York      Doctor
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin      Doctor
3  Linda   42    London        Eng.

In [21]:
#I only want to see those people whose age is above 30

In [22]:
df2[df2["Age"] > 30]  #Single Condition

    Name  Age    City Designation
1   Anna   34   Paris        Eng.
3  Linda   42  London        Eng.

In [23]:
#I only want poeple whose age is above 30 and their city must be paris

In [24]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]  #Multiple Conditions

   Name  Age   City Designation
1  Anna   34  Paris        Eng.

# **8. Basic Functions**

In [25]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df.head()        # first 5 rows

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df.tail()        # last 5 rows

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df.shape         # (rows, columns)

(4, 4)

In [29]:
df.columns       # column names

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [30]:
df.info()        # data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Salary  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [31]:
df.describe()    # statistics

             Age        Salary
count   4.000000      4.000000
mean   33.250000  70500.000000
std     6.396614  10214.368964
min    28.000000  62000.000000
25%    28.750000  64250.000000
50%    31.500000  67500.000000
75%    36.000000  73750.000000
max    42.000000  85000.000000

# **9. Sorting**

In [32]:
df.sort_values(by="Salary", ascending=False)

    Name  Age      City  Salary
3  Linda   42    London   85000
1   Anna   34     Paris   70000
0   John   28  New York   65000
2  Peter   29    Berlin   62000

# **10. Handling Missing Values**

In [33]:
df.isnull()          # check nulls

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False  False   False

In [34]:
df.dropna()          # remove null rows

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
df.fillna(0)         # replace nulls

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# **11. GroupBy**

In [36]:
df.groupby("City")["Salary"].mean()

City
Berlin      62000.0
London      85000.0
New York    65000.0
Paris       70000.0
Name: Salary, dtype: float64

# **12. Reading Files**

In [38]:
df = pd.DataFrame({ "Name":["Alice","Bob"], "Age":[20,21] })

In [39]:
df.to_csv("data.csv", index=False)  # creates file

In [40]:
df2 = pd.read_csv("data.csv")       # reads it back
print(df2)

    Name  Age
0  Alice   20
1    Bob   21

**To Know**

In [41]:
import os
print(os.getcwd())   # To check current folder where Python is searching.

/content

In [42]:
import os
print(os.listdir())   # To see available files

['.config', 'data.csv', 'sample_data']

In [ ]:
df = pd.read_csv("C:/Users/Koushal/Documents/data.csv")  # If file is somewhere else

In [ ]:
df = pd.read_csv("/content/data.csv")   # Colab