In [28]:
import numpy as np
import pandas as pd

# **1. Finding Missing Data**

In [29]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [30]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.isna()        # or df.isnull()   It Returns DataFrame of True/False

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [32]:
df.isna().sum()      # Count missing values per column

A    1
B    0
C    2
D    3
dtype: int64

In [33]:
df.isna().any()      # Check if any missing values exist

A     True
B    False
C     True
D     True
dtype: bool

In [34]:
df.isna().sum().sum()    # Total missing values in entire dataset

np.int64(6)

# **2. Removing Missing Data**

In [35]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

**Drop Rows**

In [36]:
df.dropna()    # Removes rows with any NaN

     A  B    C    D
0  1.0  1  1.0  1.0

**Drop Columns**

In [37]:
df.dropna(axis=1)  # Removes columns with any NaN

   B
0  1
1  2
2  3
3  4
4  5

**Threshold Concept**

In [38]:
df.dropna(thresh=3)      # Keep rows with at least 3 non-NaN values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**Drop Based on Specific Columns**

In [39]:
df.dropna(subset=['A', 'C'])   # Drops rows where A or C is NaN

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN

# **3. Filling the missing Data**

In [40]:
df.fillna(0)    # Fill with Constant

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [41]:
df.fillna({'A':0, 'B':100, 'C':300})     # Fill with Different Values

     A  B      C    D
0  1.0  1    1.0  1.0
1  2.0  2    2.0  NaN
2  0.0  3    3.0  NaN
3  4.0  4  300.0  NaN
4  5.0  5  300.0  5.0

In [42]:
df.fillna(df.mean())  # Fill with Mean

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [43]:
df.fillna(df.median())    # Fill with median

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [44]:
df.fillna(df.mode().iloc[0])      # Fill with Mode

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  1.0  3  3.0  1.0
3  4.0  4  1.0  1.0
4  5.0  5  1.0  5.0

Interview Tip:

*   Mean → Normal distribution
*   Median → Skewed data
*   Mode → Categorical data

# **4. Forward / Backward Fill**

In [45]:
df.fillna(method='ffill')   # Forward Fill (propagate previous value)

/tmp/ipykernel_6746/3146767054.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')   # Forward Fill (propagate previous value)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  2.0  3  3.0  1.0
3  4.0  4  3.0  1.0
4  5.0  5  3.0  5.0

In [46]:
df.fillna(method='bfill')     # Backward Fill

/tmp/ipykernel_6746/2434671675.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')     # Backward Fill

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  5.0
2  4.0  3  3.0  5.0
3  4.0  4  NaN  5.0
4  5.0  5  NaN  5.0

In [47]:
df.ffill()

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  2.0  3  3.0  1.0
3  4.0  4  3.0  1.0
4  5.0  5  3.0  5.0

In [48]:
df.bfill()

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  5.0
2  4.0  3  3.0  5.0
3  4.0  4  NaN  5.0
4  5.0  5  NaN  5.0

# **5. Interpolation**

In [49]:
df.interpolate()    # Fills missing values using trend (linear by default)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  2.0
2  3.0  3  3.0  3.0
3  4.0  4  3.0  4.0
4  5.0  5  3.0  5.0

# **6. Important Edge Cases**

In [50]:
df['A'].isna().sum()     # Check Missing in Specific Column

np.int64(1)

In [51]:
df.replace(0, np.nan)     # Replace Specific Values with NaN

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [52]:
df.fillna(0, inplace=True)     # Inplace Modification

# **7. When to Drop vs Fill (Concept Question)**

| Situation                | What to Do     |
| ------------------------ | -------------- |
| Few missing values       | Drop           |
| Many missing values      | Fill           |
| Important column         | Fill carefully |
| Entire column mostly NaN | Drop column    |