In [60]:
import numpy as np
import pandas as pd

# **1. Merging 2 dataframes**

In [61]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [62]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [63]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

**1. Inner Join**

In [64]:
pd.merge(employees,salaries,on='employee_id',how ='inner')  # Common rows only.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

**2. Left Join**

In [65]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

**3. Right Join**

In [66]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**4. Outer Join**

In [67]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

**5. Merge with Indicator**

In [68]:
pd.merge(
  employees,
  salaries,
  on='employee_id',
  how='outer',
  indicator=True             # Shows source of rows.
)

   employee_id   name department   salary    bonus      _merge
0            1   John         HR  60000.0   5000.0        both
1            2   Anna         IT  80000.0  10000.0        both
2            3  Peter    Finance  65000.0   7000.0        both
3            4  Linda         IT      NaN      NaN   left_only
4            5    Bob         HR      NaN      NaN   left_only
5            6    NaN        NaN  70000.0   8000.0  right_only
6            7    NaN        NaN  90000.0  12000.0  right_only

**6. Selecting Custom Suffixes**

In [69]:
salaries['department']=['HR','IT','Finance','Admin','Sales']

In [70]:
pd.merge(
 employees,
 salaries,
 on='employee_id',
 suffixes=('_emp','_sal')
)

   employee_id   name department_emp  salary  bonus department_sal
0            1   John             HR   60000   5000             HR
1            2   Anna             IT   80000  10000             IT
2            3  Peter        Finance   65000   7000        Finance

**7. Merge on Multiple Columns**

In [71]:
pd.merge(
 employees,
 salaries,
 on=['employee_id'],
 how='inner'
)

   employee_id   name department_x  salary  bonus department_y
0            1   John           HR   60000   5000           HR
1            2   Anna           IT   80000  10000           IT
2            3  Peter      Finance   65000   7000      Finance

**8. Cross Join**

In [72]:
pd.merge(
 employees,
 salaries,              # Cartesian product.
 how='cross'            # Every employee with every salary row.
)

,employee_id_x,name,department_x,employee_id_y,salary,bonus,department_y
0,1,John,HR,1,60000,5000,HR
1,1,John,HR,2,80000,10000,IT
2,1,John,HR,3,65000,7000,Finance
3,1,John,HR,6,70000,8000,Admin
4,1,John,HR,7,90000,12000,Sales
5,2,Anna,IT,1,60000,5000,HR
6,2,Anna,IT,2,80000,10000,IT
7,2,Anna,IT,3,65000,7000,Finance
8,2,Anna,IT,6,70000,8000,Admin
9,2,Anna,IT,7,90000,12000,Sales
10,3,Peter,Finance,1,60000,5000,HR
11,3,Peter,Finance,2,80000,10000,IT
12,3,Peter,Finance,3,65000,7000,Finance
13,3,Peter,Finance,6,70000,8000,Admin
14,3,Peter,Finance,7,90000,12000,Sales
15,4,Linda,IT,1,60000,5000,HR
16,4,Linda,IT,2,80000,10000,IT
17,4,Linda,IT,3,65000,7000,Finance
18,4,Linda,IT,6,70000,8000,Admin
19,4,Linda,IT,7,90000,12000,Sales
20,5,Bob,HR,1,60000,5000,HR
21,5,Bob,HR,2,80000,10000,IT
22,5,Bob,HR,3,65000,7000,Finance
23,5,Bob,HR,6,70000,8000,Admin
24,5,Bob,HR,7,90000,12000,Sales

**9. Validate Merge**

In [73]:
pd.merge(
 employees,
 salaries,
 on='employee_id',
 validate='one_to_one'        # Both tables must have unique values in the merge key.
)

   employee_id   name department_x  salary  bonus department_y
0            1   John           HR   60000   5000           HR
1            2   Anna           IT   80000  10000           IT
2            3  Peter      Finance   65000   7000      Finance

In [74]:
pd.merge(
 employees,
 salaries,
 on='employee_id',
 validate='one_to_many'      # Left table key unique, right table may have duplicates.
)

   employee_id   name department_x  salary  bonus department_y
0            1   John           HR   60000   5000           HR
1            2   Anna           IT   80000  10000           IT
2            3  Peter      Finance   65000   7000      Finance

In [75]:
pd.merge(
 employees,
 salaries,
 on='employee_id',
 validate='many_to_one'      # Left table can have duplicates, right table unique.
)

   employee_id   name department_x  salary  bonus department_y
0            1   John           HR   60000   5000           HR
1            2   Anna           IT   80000  10000           IT
2            3  Peter      Finance   65000   7000      Finance

In [76]:
pd.merge(
 employees,
 salaries,
 on='employee_id',
 validate='many_to_many'      # Duplicates allowed in both tables.
)

   employee_id   name department_x  salary  bonus department_y
0            1   John           HR   60000   5000           HR
1            2   Anna           IT   80000  10000           IT
2            3  Peter      Finance   65000   7000      Finance

**Real-world mapping for validate merge**



*   Employee ↔ Salary → one_to_one
*   Customer ↔ Orders → one_to_many
*   Transactions ↔ Product Master → many_to_one
*   Students ↔ Courses (many enrollments) → many_to_many

Validate helps detect wrong merges and duplicate key issues

# **2. Concatenation of 2 dataframes**

In [77]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [78]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [79]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

**Row Wise**

In [80]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

**Reset Index**

In [81]:
pd.concat(
 [df1,df2],
 ignore_index=True
)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5

**Column Wise**

In [82]:
pd.concat(
 [df1,df2],
 axis=1           # Column Wise
)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Keys (Multi Index)**

In [83]:
pd.concat(
 [df1,df2],
 keys=['first','second']
)

           A   B   C
first  0  A0  B0  C0
       1  A1  B1  C1
       2  A2  B2  C2
second 0  A3  B3  C3
       1  A4  B4  C4
       2  A5  B5  C5

# **3. Joining data frames**
Index based.

In [84]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [85]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [86]:
df2

   score
2     85
3     90
4     75

**Default Left Join**

In [87]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

**Outer Join**

In [88]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

**Right Style Using Join**

In [89]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

**Join with Suffix**

In [90]:
df2['name']=['X','Y','Z']     # Suppose both have "name"

In [91]:
df1.join(
df2,
lsuffix='_left',
rsuffix='_right'
)

  name_left  score name_right
1     Alice    NaN        NaN
2       Bob   85.0          X
3   Charlie   90.0          Y

# **4) Handle Missing Data After Merge**

In [92]:
pd.merge(
 employees,
 salaries,
 how='outer'
).fillna(0)    # replaces missing values with 0, keep all rows

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      0.0      0.0
4            5    Bob         HR      0.0      0.0
5            6      0      Admin  70000.0   8000.0
6            7      0      Sales  90000.0  12000.0

In [93]:
pd.merge(
 employees,
 salaries,
 how='outer'
).dropna()      # remove rows having missing values

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0

# **5) Remove Duplicate Rows After Combining**

In [94]:
pd.concat([df1,df2]).drop_duplicates()

      name  score
1    Alice    NaN
2      Bob    NaN
3  Charlie    NaN
2        X   85.0
3        Y   90.0
4        Z   75.0

# **6) Merge on Different Column Names**

In [95]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [96]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [97]:
salaries.columns = ['emp_id','salary','bonus']

In [98]:
salaries

   emp_id  salary  bonus
0       1   60000   5000
1       2   80000  10000
2       3   65000   7000
3       6   70000   8000
4       7   90000  12000

In [99]:
pd.merge(
 employees,
 salaries,
 left_on='employee_id',
 right_on='emp_id'
)

   employee_id   name department  emp_id  salary  bonus
0            1   John         HR       1   60000   5000
1            2   Anna         IT       2   80000  10000
2            3  Peter    Finance       3   65000   7000

# **7) Difference**

In [101]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

**merge()**

In [102]:
pd.merge(employees,salaries)     # Column based

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [103]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

**join()**

In [104]:
df1.join(df2)     # Index based

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

**concat()**

In [105]:
pd.concat([df1,df2])      # Stacking

      name  score
1    Alice    NaN
2      Bob    NaN
3  Charlie    NaN
2      NaN   85.0
3      NaN   90.0
4      NaN   75.0