In [1]:
import numpy as np
import pandas as pd

# **Pivot Tables**

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    457     52   John  January      Q1
1  2023-01-02       B   West    134     48   Mary  January      Q1
2  2023-01-03       C  North    990     67    Bob  January      Q1
3  2023-01-04       D  South    858     39  Alice  January      Q1
4  2023-01-05       A   East    203     81   John  January      Q1
5  2023-01-06       B   West    710     19   Mary  January      Q1
6  2023-01-07       C  North    311     68    Bob  January      Q1
7  2023-01-08       D  South    804     30  Alice  January      Q1
8  2023-01-09       A   East    667     50   John  January      Q1
9  2023-01-10       B   West    722     91   Mary  January      Q1
10 2023-01-11       C  North    809     20    Bob  January      Q1
11 2023-01-12       D  South    553     79  Alice  January      Q1
12 2023-01-13       A   East    822     94   John  January      Q1
13 2023-01-14       B   West    294     76   Mary  January      Q1
14 2023-01-15       C  North    631     93    Bob  January      Q1
15 2023-01-16       D  South    161     74  Alice  January      Q1
16 2023-01-17       A   East    551     58   John  January      Q1
17 2023-01-18       B   West    324     29   Mary  January      Q1
18 2023-01-19       C  North    284     70    Bob  January      Q1
19 2023-01-20       D  South    283     49  Alice  January      Q1

# **1. Basic Pivot Table**

In [3]:
pd.pivot_table(df, values="Sales", index="Region", columns="Product", aggfunc="median")

Product      A      B      C      D
Region
East     551.0    NaN    NaN    NaN
North      NaN    NaN  631.0    NaN
South      NaN    NaN    NaN  553.0
West       NaN  324.0    NaN    NaN

# **2. Multiple Aggregations**

In [4]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Product",                      # It shows you know multi-metric analysis
               aggfunc=['mean', 'sum', 'max'])         # Multi-level column headers (mean, sum, max)

          mean                          sum                            max  \
Product      A      B      C      D       A       B       C       D      A
Region
East     540.0    NaN    NaN    NaN  2700.0     NaN     NaN     NaN  822.0
North      NaN    NaN  605.0    NaN     NaN     NaN  3025.0     NaN    NaN
South      NaN    NaN    NaN  531.8     NaN     NaN     NaN  2659.0    NaN
West       NaN  436.8    NaN    NaN     NaN  2184.0     NaN     NaN    NaN


Product      B      C      D
Region
East       NaN    NaN    NaN
North      NaN  990.0    NaN
South      NaN    NaN  858.0
West     722.0    NaN    NaN

# **3. Multiple Values**

In [7]:
pd.pivot_table(df,
               values=['Sales', 'Units'],                # It produces Hierarchical columns (Sales, Units)
               index='Region',
               columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     540.0    NaN    NaN    NaN  67.0   NaN   NaN   NaN
North      NaN    NaN  605.0    NaN   NaN   NaN  63.6   NaN
South      NaN    NaN    NaN  531.8   NaN   NaN   NaN  54.2
West       NaN  436.8    NaN    NaN   NaN  52.6   NaN   NaN

# **4. Fill Missing Values**

In [8]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Product",
               fill_value=0)                       # It avoids NaN in reports

Product      A      B      C      D
Region
East     540.0    0.0    0.0    0.0
North      0.0    0.0  605.0    0.0
South      0.0    0.0    0.0  531.8
West       0.0  436.8    0.0    0.0

# **5. Margins (Grand Total)**

In [9]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Product",
               aggfunc="sum",
               margins=True)                    # It adds all row & column (totals)

Product       A       B       C       D    All
Region
East     2700.0     NaN     NaN     NaN   2700
North       NaN     NaN  3025.0     NaN   3025
South       NaN     NaN     NaN  2659.0   2659
West        NaN  2184.0     NaN     NaN   2184
All      2700.0  2184.0  3025.0  2659.0  10568

# **6. Group by Multiple Columns**

In [10]:
pd.pivot_table(df,
               values="Sales",
               index=['Region', 'Rep'],         # Use case: Region + Representative analysis
               columns='Product',
               aggfunc='sum')

Product            A       B       C       D
Region Rep
East   John   2700.0     NaN     NaN     NaN
North  Bob       NaN     NaN  3025.0     NaN
South  Alice     NaN     NaN     NaN  2659.0
West   Mary      NaN  2184.0     NaN     NaN

# **7. Using Month / Quarter**

In [11]:
pd.pivot_table(df,
               values="Sales",
               index='Month',           # Time-based analysis = real-world scenario
               columns='Product',
               aggfunc='sum')

Product     A     B     C     D
Month
January  2700  2184  3025  2659

In [12]:
pd.pivot_table(df,
               values="Sales",
               index='Quarter',         # Time-based analysis = real-world scenario
               columns='Region',
               aggfunc='mean')

Region    East  North  South   West
Quarter
Q1       540.0  605.0  531.8  436.8

# **8. Custom Aggregation**

In [13]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Product",
               aggfunc=lambda x: x.max() - x.min())     # It gives range of sales per group

Product      A      B      C      D
Region
East     619.0    NaN    NaN    NaN
North      NaN    NaN  706.0    NaN
South      NaN    NaN    NaN  697.0
West       NaN  588.0    NaN    NaN

# **9. Pivot vs Pivot Table**

**Pivot (No aggregation)**



```
df.pivot(index="Region", columns="Product", values="Sales")
```

It fails if duplicate entries exist

**Pivot Table (Aggregation allowed)**

In [16]:
pd.pivot_table(df, values="Sales", index="Region", columns="Product")    # Handles duplicates using aggregation

Product      A      B      C      D
Region
East     540.0    NaN    NaN    NaN
North      NaN    NaN  605.0    NaN
South      NaN    NaN    NaN  531.8
West       NaN  436.8    NaN    NaN

# **CROSSTAB (Frequency Analysis)**

# **10. Basic Crosstab**

In [17]:
pd.crosstab(df['Region'], df['Product'])    # Counts occurrences

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# **11. Normalization**

In [18]:
pd.crosstab(df['Region'], df['Product'], normalize='index')       # Shows Row-wise percentage

Product    A    B    C    D
Region
East     1.0  0.0  0.0  0.0
North    0.0  0.0  1.0  0.0
South    0.0  0.0  0.0  1.0
West     0.0  1.0  0.0  0.0

In [19]:
pd.crosstab(df['Region'], df['Product'], normalize='columns')       # Shows Column-wise percentage

Product    A    B    C    D
Region
East     1.0  0.0  0.0  0.0
North    0.0  0.0  1.0  0.0
South    0.0  0.0  0.0  1.0
West     0.0  1.0  0.0  0.0

In [20]:
pd.crosstab(df['Region'], df['Product'], normalize=True)          # Shows Overall percentage

Product     A     B     C     D
Region
East     0.25  0.00  0.00  0.00
North    0.00  0.00  0.25  0.00
South    0.00  0.00  0.00  0.25
West     0.00  0.25  0.00  0.00

# **12. Crosstab with Aggregation**

In [21]:
pd.crosstab(df['Region'],
            df['Product'],
            values=df['Sales'],
            aggfunc='sum')              # Now behaves like pivot table

Product       A       B       C       D
Region
East     2700.0     NaN     NaN     NaN
North       NaN     NaN  3025.0     NaN
South       NaN     NaN     NaN  2659.0
West        NaN  2184.0     NaN     NaN

# **13. Add Margins in Crosstab**

In [22]:
pd.crosstab(df['Region'],
            df['Product'],
            margins=True)

Product  A  B  C  D  All
Region
East     5  0  0  0    5
North    0  0  5  0    5
South    0  0  0  5    5
West     0  5  0  0    5
All      5  5  5  5   20

You should be confident in:

1. Difference between:
pivot() vs pivot_table()

2. Handling:
Missing values (fill_value) vs
Totals (margins)

3. Multi-level:Multiple values vs
Multiple aggfunc

4. Time-based:
Month, Quarter

5. Crosstab:
Frequency vs percentage &
Aggregation inside crosstab