In [1]:
import numpy as np
import pandas as pd

# **1. DataFrames Basic Operations**

In [2]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [3]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
df1.shape

(5, 3)

In [5]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [7]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

# **2. Column Operations**

**Access Column**

In [8]:
df1['A']

0    1
1    2
2    3
3    4
4    5
Name: A, dtype: int64

**Multiple Columns**

In [9]:
df1[['A', 'B']]

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

**Add New Column**

In [10]:
df1['E'] = df1['A'] + df1['B']
df1['E']

0    11
1    22
2    33
3    44
4    55
Name: E, dtype: int64

**Delete Column**

In [11]:
df1.drop('E', axis=1, inplace=True)
print(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

# **3. Row Operations**

**Access Row (by index)**

In [12]:
df1.loc[0]

A      1
B     10
C    100
Name: 0, dtype: int64

**Access Multiple Rows**

In [13]:
df1.loc[0:2]

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300

**Access by Position**

In [14]:
df1.iloc[0]

A      1
B     10
C    100
Name: 0, dtype: int64

# **4. Filtering Data**

**Single Condition**

In [15]:
df1[df1['A'] > 2]

   A   B    C
2  3  30  300
3  4  40  400
4  5  50  500

**Multiple Conditions**

In [16]:
df1[(df1['A'] > 2) & (df1['B'] < 50)]

   A   B    C
2  3  30  300
3  4  40  400

# **5. Sorting**

**Sort by One Column**

In [17]:
df1.sort_values(by='B')

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

**Descending Order**

In [18]:
df1.sort_values(by='B', ascending=False)

   A   B    C
4  5  50  500
3  4  40  400
2  3  30  300
1  2  20  200
0  1  10  100

# **6. Applying Functions**

In [19]:
df1['D'] = df1["B"].apply(lambda x: x**2)
df1['D']

0     100
1     400
2     900
3    1600
4    2500
Name: D, dtype: int64

**Apply on Multiple Columns**

In [20]:
df1[['A', 'B']].apply(lambda x: x + 1)

   A   B
0  2  11
1  3  21
2  4  31
3  5  41
4  6  51

# **7. Aggregation Functions**

In [21]:
df1['A'].sum()

np.int64(15)

In [22]:
df1['B'].mean()

np.float64(30.0)

In [23]:
df1['C'].max()

500

In [24]:
df1['A'].min()

1

# **8. GroupBy**

In [25]:
df2 = pd.DataFrame({
    'A': ['X', 'Y', 'X', 'Y', 'X'],
    'B': [10, 20, 30, 40, 50]
})
df2

   A   B
0  X  10
1  Y  20
2  X  30
3  Y  40
4  X  50

**Group and Sum**

In [26]:
df2.groupby('A')['B'].sum()

A
X    90
Y    60
Name: B, dtype: int64

# **9. Handling Missing Values**

In [27]:
df1.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

In [28]:
df1.isnull().sum()

A    0
B    0
C    0
D    0
dtype: int64

**Fill Missing Values**

In [29]:
df1.fillna(0)

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

**Drop Missing Values**

In [30]:
df1.dropna()

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

# **10. Renaming Columns**

In [31]:
df1.rename(columns={'B': 'Alpha'}, inplace=True)
df1

   A  Alpha    C     D
0  1     10  100   100
1  2     20  200   400
2  3     30  300   900
3  4     40  400  1600
4  5     50  500  2500

# **11. Index Operations**

In [32]:
df1.set_index('A', inplace=True)
df1 = df1.reset_index()

# **12. Unique & Value Counts**

In [33]:
df1['A'].unique()

array([1, 2, 3, 4, 5])

In [34]:
df1['A'].value_counts()

A
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64

In [35]:
df1

   A  Alpha    C     D
0  1     10  100   100
1  2     20  200   400
2  3     30  300   900
3  4     40  400  1600
4  5     50  500  2500

# **13. Basic Arithmetic Operations**

In [36]:
df1['A'] + df1.index

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [37]:
print(df1.columns)

Index(['A', 'Alpha', 'C', 'D'], dtype='object')

In [38]:
df1 = df1.reset_index()
df1['A'] + df1['C']

0    101
1    202
2    303
3    404
4    505
dtype: int64

# **14. Conditional Column Creation**

In [40]:
df1['F'] = df1['A'].apply(lambda x: 'High' if x > 3 else 'Low')
df1['F']

0     Low
1     Low
2     Low
3    High
4    High
Name: F, dtype: object

# **15. Checking Duplicates**

In [42]:
df1.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [44]:
df1.drop_duplicates()

   index  A  Alpha    C     D     F
0      0  1     10  100   100   Low
1      1  2     20  200   400   Low
2      2  3     30  300   900   Low
3      3  4     40  400  1600  High
4      4  5     50  500  2500  High